### ISSUE TITLE
panic: escapeSpaces: string should contain no more than a single '=':

### ISSUE THREAD

**Issue by XV25** [ntorresalberto/dogi#2]
Hi,

So I have this new weird bug with latest dogi version (4d8d633d); the "dogi run" command do not work anymore : 

'''
dogi: imageName: os_ros
dogi: temp xauth file: /tmp/.dogi2210917500.xauth
dogi: env DISPLAY=:1
dogi: current dir: /home/auctus/dogi
dogi: workdir: /home/auctus/dogi
dogi: /dev/dri/card1 found, nvidia card? (3D might not work)
dogi: dogi path:/home/auctus/go/bin/dogi
dogi: set container name: ros_doc
dogi: adding --network=host
dogi: using apt-cacher, disable it with --no-cacher
dogi: build apt cacher image: dogi/apt-cacher
dogi: temp dir: /tmp/dogi_apt-cache100848071
dogi: temp Dockerfile: /tmp/dogi_apt-cache100848071/Dockerfile
dogi: need to restart apt cache container
dogi: container running, stopping...
dogi: container exists, removing...
dogi: container dogi_apt-cacher_cont not found, launching...
dogi: apt-cacher container started
dogi: container dogi_apt-cacher_cont found: 172.17.0.2
dogi: apt-cacher file: /tmp/.dogi_apt-cacher_2012402245
dogi: imageCmd: [ /bin/sh, -c, /usr/bin/bash -c "source /script.sh && source /opt/ros/noetic/setup.bash && /usr/bin/bash" ]
dogi: execCommand list: /bin/sh, -c, /usr/bin/bash -c "source /script.sh && source /opt/ros/noetic/setup.bash && /usr/bin/bash"
dogi: mount usb devices with correct permissions
dogi: supported distro image detected: Ubuntu
dogi: create user script: /tmp/.dogi910099597.sh
dogi: user doesn't belong to group realtime, won't add it to container
dogi: entrypoint: [bash /dogi_create_user.sh /bin/sh -c /usr/bin/bash -c "source /script.sh && source /opt/ros/noetic/setup.bash && /usr/bin/bash"]
panic: escapeSpaces: string should contain no more than a single '=':
/usr/bin/bash -c "source /script.sh && source /opt/ros/noetic/setup.bash && /usr/bin/bash"'

goroutine 1 [running]:
github.com/ntorresalberto/dogi/cmd.escapeSpaces({0xc000384000, 0x1f, 0x5?})
	/home/auctus/go/pkg/mod/github.com/ntorresalberto/dogi@v0.0.0-20240328115531-4d8d633d676c/cmd/root.go:239 +0x22e
github.com/ntorresalberto/dogi/cmd.mergeEscapeSpaces(...)
	/home/auctus/go/pkg/mod/github.com/ntorresalberto/dogi@v0.0.0-20240328115531-4d8d633d676c/cmd/root.go:250
github.com/ntorresalberto/dogi/cmd.glob..func9(0x76e340?, {0xc0001a7800?, 0x1, 0x3})
	/home/auctus/go/pkg/mod/github.com/ntorresalberto/dogi@v0.0.0-20240328115531-4d8d633d676c/cmd/run.go:770 +0x267c
github.com/spf13/cobra.(*Command).execute(0x76e340, {0xc0001a7770, 0x3, 0x3})
	/home/auctus/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x76e060)
	/home/auctus/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/auctus/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/ntorresalberto/dogi/cmd.Execute()
	/home/auctus/go/pkg/mod/github.com/ntorresalberto/dogi@v0.0.0-20240328115531-4d8d633d676c/cmd/root.go:262 +0x25
main.main()
	/home/auctus/go/pkg/mod/github.com/ntorresalberto/dogi@v0.0.0-20240328115531-4d8d633d676c/main.go:11 +0x8a
'''

The issue dissapears with dogi 4d8d633-dirty.

Do you have any idea of what could be the cause of this bug? 

Thanks you for your work, and have a nice day!

**Comment by ntorresalberto** [comment]
it should be solved in the latest version (you can try it with `dogi update`)
if it's not solved, reopen the issue please
